### ISSUE TITLE
[Sample App: RNA-seq] Warning

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.modules.hermes#271] opened 2022-07-25 11:34 UTC
When run `teal.gallery::launch_app("RNA-seq")` we get a warning:

```
Warning in is.na(varlabels) || varlabels == "" :
  'length(x) = 72 > 1' in coercion to 'logical(1)'
Warning in is.na(varlabels) || varlabels == "" :
  'length(x) = 72 > 1' in coercion to 'logical(1)'
```

sessionInfo:

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] teal.modules.hermes_0.1.3.9007   teal.modules.general_0.2.14.9008 shinyTree_0.2.7                 
 [4] ggmosaic_0.3.3                   MultiAssayExperiment_1.22.0      SummarizedExperiment_1.26.1     
 [7] Biobase_2.56.0                   GenomicRanges_1.48.0             GenomeInfoDb_1.32.2             
[10] IRanges_2.30.0                   S4Vectors_0.34.0                 BiocGenerics_0.42.0             
[13] MatrixGenerics_1.8.1             matrixStats_0.62.0               testthat_3.1.4                  
[16] teal_0.11.1.9014                 teal.transform_0.1.1.9009        magrittr_2.0.3                  
[19] teal.data_0.1.1.9009             shiny_1.7.1                      ggplot2_3.3.6                   

loaded via a namespace (and not attached):
  [1] utf8_1.2.2                tidyselect_1.1.2          RSQLite_2.2.14           
  [4] AnnotationDbi_1.58.0      htmlwidgets_1.5.4         grid_4.2.1               
  [7] BiocParallel_1.30.3       showimage_1.0.0           devtools_2.4.3           
 [10] teal.gallery_0.1.0.9007   munsell_0.5.0             codetools_0.2-18         
 [13] DT_0.23                   withr_2.5.0               colorspace_2.0-3         
 [16] filelock_1.0.2            ggfortify_0.4.14          logger_0.2.2             
 [19] knitr_1.39                rstudioapi_0.13           rtables_0.5.1.6          
 [22] shinyWidgets_0.7.0        Rdpack_2.3.1              labeling_0.4.2           
 [25] git2r_0.30.1              pingr_2.0.1               GenomeInfoDbData_1.2.8   
 [28] bit64_4.0.5               farver_2.1.1              rprojroot_2.0.3          
 [31] vctrs_0.4.1               generics_0.1.3            xfun_0.31                
 [34] BiocFileCache_2.4.0       R6_2.5.1                  doParallel_1.0.17        
 [37] clue_0.3-61               locfit_1.5-9.5            bitops_1.0-7             
 [40] cachem_1.0.6              DelayedArray_0.22.0       assertthat_0.2.1         
 [43] promises_1.2.0.1          scales_1.2.0              debugme_1.1.0            
 [46] gtable_0.3.0              processx_3.7.0            shinytest_1.5.1          
 [49] rlang_1.0.4               genefilter_1.78.0         GlobalOptions_0.1.2      
 [52] splines_4.2.1             lazyeval_0.2.2            broom_1.0.0              
 [55] checkmate_2.1.0           yaml_2.3.5                crosstalk_1.2.0          
 [58] backports_1.4.1           httpuv_1.6.5              usethis_2.1.6            
 [61] tools_4.2.1               ellipsis_0.3.2            jquerylib_0.1.4          
 [64] RColorBrewer_1.1-3        sessioninfo_1.2.2         Rcpp_1.0.9               
 [67] base64enc_0.1-3           progress_1.2.2            zlibbioc_1.42.0          
 [70] shinyRadioMatrix_0.2.1    purrr_0.3.4               RCurl_1.98-1.7           
 [73] ps_1.7.1                  scda_0.1.3.9010           prettyunits_1.1.1        
 [76] GetoptLong_1.0.5          fontawesome_0.2.2         ggrepel_0.9.1            
 [79] cluster_2.1.3             fs_1.5.2                  data.table_1.14.2        
 [82] circlize_0.4.15           pkgload_1.3.0             hms_1.1.1                
 [85] shinyjs_2.1.0             mime_0.12                 evaluate_0.15            
 [88] xtable_1.8-4              webdriver_1.0.6           XML_3.99-0.10            
 [91] gridExtra_2.3             shape_1.4.6               compiler_4.2.1           
 [94] biomaRt_2.52.0            tibble_3.1.7              crayon_1.5.1             
 [97] htmltools_0.5.2           later_1.3.0               tidyr_1.2.0              
[100] geneplotter_1.74.0        DBI_1.1.3                 tern_0.7.8.9023          
[103] dbplyr_2.2.1              ComplexHeatmap_2.12.0     rappdirs_0.3.3           
[106] Matrix_1.4-1              brio_1.1.3                cli_3.3.0                
[109] rbibutils_2.2.8           parallel_4.2.1            forcats_0.5.1            
[112] pkgconfig_2.0.3           plotly_4.10.0             xml2_1.3.3               
[115] foreach_1.5.2             annotate_1.74.0           bslib_0.3.1              
[118] staged.dependencies_0.2.7 teal.reporter_0.1.0.9022  XVector_0.36.0           
[121] rematch_1.0.1             teal.widgets_0.1.1.9006   stringr_1.4.0            
[124] callr_3.7.0               digest_0.6.29             Biostrings_2.64.0        
[127] rmarkdown_2.14            edgeR_3.38.1              curl_4.3.2               
[130] teal.logger_0.1.0.9011    rjson_0.2.21              lifecycle_1.0.1          
[133] jsonlite_1.8.0            desc_1.4.1                viridisLite_0.4.0        
[136] limma_3.52.2              fansi_1.0.3               pillar_1.7.0             
[139] lattice_0.20-45           KEGGREST_1.36.2           fastmap_1.1.0            
[142] httr_1.4.3                pkgbuild_1.3.1            survival_3.3-1           
[145] parsedate_1.3.0           glue_1.6.2                hermes_0.99.5.9008       
[148] remotes_2.4.2             png_0.1-7                 iterators_1.0.14         
[151] bit_4.0.4                 stringi_1.7.8             sass_0.4.1               
[154] blob_1.2.3                DESeq2_1.36.0             formatters_0.3.2.4       
[157] teal.slice_0.1.1.9009     memoise_2.0.1             renv_0.15.4              
[160] dplyr_1.0.9   
```

**Comment by danielinteractive** [comment] 2022-07-26 00:23
Thanks @Polkas , we have also seen that recently when developing helios modules - so I think this is coming from `teal`

**Comment by gogonzo** [comment] 2022-07-28 13:50
Source of the problem is here
https://github.com/insightsengineering/teal.slice/blob/09c6ab2e026325b62c790c3759ac414701457a62/R/FilterStates.R#L1456

**Comment by BLAZEWIM** [comment] 2022-08-08 13:09
Similar issue:
https://stackoverflow.com/a/72848495
so it happens in R > 4.2 (I could not reproduce in 4.0.3).

**Comment by BLAZEWIM** [comment] 2022-08-12 14:39
closed by https://github.com/insightsengineering/teal.slice/pull/86

**Closed by BLAZEWIM** 2022-08-12 14:39 UTC
Labels: core
